// <auto-generated />
using System;
using LLM_TriageAgent.API.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LLM_TriageAgent.API.Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614220341_InitialProductionSchemaSetup")]
    partial class InitialProductionSchemaSetup
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("triage")
                .HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("LLM_TriageAgent.API.Models.SupportTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AgentReply")
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedLabel")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SupportTickets", "triage");
                });
#pragma warning restore 612, 618
        }
    }
}
